# Generated by Django 6.0.6 on 2026-06-14 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reciepieitem',
            old_name='ingredient_name',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='reciepieitem',
            old_name='recipie_name',
            new_name='recipie',
        ),
    ]
