# Generated by Django 6.0.6 on 2026-06-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0002_rename_ingredient_name_reciepieitem_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_img',
            field=models.ImageField(null=True, upload_to='recicipie_images'),
        ),
    ]
