# Generated by Django 6.0.6 on 2026-06-17 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0003_recipie_recipie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='recipie_img',
        ),
    ]
