# Generated by Django 6.0.6 on 2026-06-22 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0004_remove_recipie_recipie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to='ingredient_image'),
        ),
    ]
