# Generated by Django 6.0.6 on 2026-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0007_order_customer_address_order_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_img',
            field=models.ImageField(null=True, upload_to='recicipie_images'),
        ),
    ]
