# Generated by Django 6.0.6 on 2026-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0008_recipie_recipie_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='recipie_img_url',
            field=models.TextField(null=True),
        ),
    ]
