# Generated by Django 6.0.6 on 2026-07-08 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0009_recipie_recipie_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipie',
            name='recipie_img',
        ),
    ]
