# Generated by Django 6.0.6 on 2026-07-08 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontmodules', '0010_remove_recipie_recipie_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciepieitem',
            name='quantity',
        ),
    ]
